### ISSUE TITLE
Consult prompt_tensor_init training source code

### ISSUE THREAD

**Issue by junchengberry** [Jingchensun/prompt_tipadapter#1]
Ms. Sun:
       Hello!
      I saw this "Prompt Tuning based Adapter for Vision-Lauguage Model Adaption", it is an innovative and good experiment, but the prompt provides the trained model, can you share the source code of the training?

**Comment by xuntianci** [comment]
Ms. Sun:
Hello!
I saw this "Prompt Tuning based Adapter for Vision-Lauguage Model Adaption", it is an innovative and good experiment, but the prompt provides the trained model, can you share the source code of the training?

**Comment by Jingchensun** [comment]
The pre-trained multi-task prompt I used is from this repo: https://github.com/sIncerass/MVLPT
